name: rx_customer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  dio: ^5.7.0
  dotted_border: ^2.1.0
  easy_date_timeline: ^1.1.3
  equatable: ^2.0.5
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  iconly: ^1.0.1
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  logger: ^2.4.0
  permission_handler: ^11.3.1
  timeago: ^3.7.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
